
###PLEASE SPECIFY INPUT DIRECTORIES AND FILES HERE
outputdir: "filtering_output/"
inputdir: "input_vcfs/"
vcf: "cattle.sv.vcf.gz"

###PLEASE SPECIFY SPECIES, CHROMOSOME, AND FIILTERING MODE (RECESSIVE OR DOMINANT)
species: "cattle"
mode: "recessive"
chr: "15"

###PLEASE SPECIFY YOUR CASE SAMPLES AND SAMPLES TO EXCLUDE (OPTIONAL). ALL REMAINING SAMPLES ARE TREATED AS CASES
#EXAMPLE: case_samples = ["sample1", "sample2", "sample3"]
"exclude_samples": []